#!/bin/sh
#
# Start inetd....
#

case "$1" in
  start)
 	echo "Starting inetd..."
	inetd
	;;
  stop)
	echo -n "Stopping inetd..."
	killall inetd
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

