#! /bin/sh
#
# System-V init script for the cron daemon
#

case "$1" in
  start)
  echo -n "Starting crond..."
  crond
	echo "done."
	;;
  stop) 
  echo -n "Stopping crond..."
  killall crond
	echo "done."
	;;
  restart) 
  echo "Restarting $DESC: $NAME"
	$0 stop
	sleep 1
	$0 start
	;;
  *) echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
